# Generated by Django 5.1.1 on 2024-09-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ip_user',
            field=models.CharField(default='0.0.0.0', max_length=100),
        ),
    ]
