# Generated by Django 5.1.1 on 2024-09-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('student', models.CharField(max_length=100)),
                ('date_check', models.CharField(default='23.09.2024 21:01', max_length=100)),
            ],
        ),
    ]
