# Generated by Django 5.1.1 on 2024-09-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_check',
            field=models.CharField(default='26.09.2024 07:34', max_length=100),
        ),
    ]
