# Generated by Django 5.1.1 on 2024-09-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_attendance_date_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_check',
            field=models.CharField(default='27.09.2024 08:13', max_length=100),
        ),
    ]
