# Generated by Django 5.1.1 on 2024-09-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0002_alter_attendance_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date_check',
            field=models.CharField(default='23.09.2024 10:49', max_length=100),
        ),
    ]
