# Generated by Django 5.1.1 on 2024-09-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0003_attendance_date_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_check',
            field=models.CharField(default='23.09.2024 21:01', max_length=100),
        ),
    ]
