# Generated by Django 5.1.1 on 2024-09-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0004_alter_attendance_date_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date_check',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_auth',
            field=models.CharField(default='26.09.2024', max_length=100),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_auth',
            field=models.CharField(default='07:34', max_length=100),
        ),
    ]
