# Generated by Django 5.1.1 on 2024-09-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0005_remove_attendance_date_check_attendance_date_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_auth',
            field=models.CharField(default='07:38', max_length=100),
        ),
    ]
