# Generated by Django 5.1.1 on 2024-09-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0006_alter_attendance_time_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_auth',
            field=models.CharField(default='27.09.2024', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_auth',
            field=models.CharField(default='08:13', max_length=100),
        ),
    ]
